meta:
  engine: 4.0.4
  name: rae-dux
  version: 0.5
  author: ajrae

presets:
  defaults:
    capx: 17
    capy: 16
    kx: cx
    ky: cy
    px: 2
    py: 2
    pinky_splay: 17
    ring_splay: -7
    home_splay: -7
    index_splay: -3

  choc_spaced:
    $extends: presets.defaults

  mx_spaced:
    $extends: presets.defaults
    capx: 18
    capy: 18
    kx: 19
    ky: 19

units:
  $extends: presets.mx_spaced

points:
  # Actual key points
  zones.matrix:
    anchor.shift: [150, -180]
    key:
      padding: ky
    rows:
      bottom:
      home:
      top:
    columns:
      pinky.key:
        spread: kx
        splay: pinky_splay
        origin: [0, -ky]
      ring.key:
        spread: kx
        stagger: ky
        splay: ring_splay
        origin: [0, -ky]
      middle.key:
        spread: kx
        stagger: ky/3
        splay: home_splay
        origin: [0, -ky]
        shift: [0.2, 0]
        bind: 0
      index.key:
        spread: kx
        stagger: -ky/3
        splay: index_splay
        origin: [0, -ky]
      inner.key:
        spread: kx
        stagger: -ky/6
        origin: [0, -ky]
  zones.thumbfan:
    anchor:
      ref: matrix_inner_bottom
      shift: [-0.25 * kx, -1.4 * ky]
    columns:
      near.key:
        spread: kx
        splay: -5
        origin: [-1.5 * kx, -0.5 * ky]
      home.key:
        spread: kx
        splay: -8
        origin: [-0.5 * kx, -0.5 * ky]
      far.key:
        spread: kx
        splay: -20
        origin: [-0.5 * kx, -0.5 * ky]
    rows.thumb:

  # Component points
  zones.mcu:
    anchor:
      ref: matrix_inner_top
      shift: [20, -36/2 + 0.4 ky]
  zones.reset:
    anchor:
      ref: matrix_inner_bottom
      shift: [27.5, -14]
  zones.slider:
    anchor:
      ref: matrix_inner_bottom
      shift: [28, 0]
  zones.jst_bat:
    anchor:
      ref: reset
      shift: [-7.5, -3.25]
  zones.info:
    anchor:
      ref: thumbfan_near_thumb
      shift: [ -1.1 kx, -0.4 ky ]

  # Outline points
  zones.outline_top_right:
    anchor:
      ref: mcu
      shift: [10, 36/2]
  zones.outline_top_left:
    anchor:
      ref: matrix_ring_top
      shift: [-1.6kx, 0.4ky] # this is arbitrary
  zones.outline_bottom_left:
    anchor:
      ref: matrix_pinky_bottom
      shift: [-0.5kx - 0.2px, -0.5ky - 0.5py]
  zones.outline_thumb_top:
    anchor:
      ref: thumbfan_far_thumb
      shift: [0.5 kx - 0.5px, 0.5 ky + 0.5 py]
  zones.outline_thumb_bottom:
    anchor:
      ref: thumbfan_far_thumb
      shift: [0.5 kx - 0.5px, -0.5 ky - 0.5 py]

outlines:
  raw:
    - what: rectangle
      where:
        - /matrix_.*/
        - /thumbfan_.*/
      size: [kx + px, ky + py]
      corner: px
      bound: true

  thumbfan_glue:
    - what: polygon
      points:
        - ref: matrix_inner_home
        - ref: outline_top_right
        - ref: reset
          shift: [0, -4]
        - ref: outline_thumb_top
        - ref: outline_thumb_bottom
        - ref: matrix_pinky_bottom
          shift: [-0.5kx, -0.5ky]

  circles_top:
    top:
      what: circle
      adjust:
        aggregate:
          method: midpoint
          parts:
            - ref: outline_top_right
            - ref: outline_top_left
            - ref: matrix_middle_top
              shift: [0, 0.5 ky + py]
      radius:
        ref: outline_top_right
    side:
      what: circle
      operation: intersect
      adjust:
        aggregate:
          method: midpoint
          parts:
            - ref: outline_bottom_left
            - ref: outline_top_left
            - ref: matrix_pinky_top
              shift: [-0.5 kx - px, 0.5 ky + py]
      radius:
        ref: outline_bottom_left
    cutoff_controller:
      what: rectangle
      operation: subtract
      adjust:
        ref: outline_top_right
        shift: [80/2 - 0.001, -200/2]
      size: [80, 200]

  circles_bottom:
    bottom:
      what: circle
      adjust:
        aggregate:
          method: midpoint
          parts:
            - ref: outline_bottom_left
            - ref: outline_thumb_bottom
            - ref: thumbfan_near_thumb
              shift: [-0.5 kx - px, -0.5 ky - py]
      radius:
        ref: outline_bottom_left
    cutoff_thumbfan:
      what: rectangle
      operation: subtract
      adjust:
        ref: outline_thumb_bottom
        shift: [30/2, 0]
      size: [30, 60]

  base_outline:
    main:
      what: outline
      name: raw
      fillet: 15
    thumbfan_glue:
      what: outline
      name: thumbfan_glue
      operation: add
    circles_top:
      what: outline
      name: circles_top
      operation: add
      fillet: 15
    circles_bottom:
      what: outline
      name: circles_bottom
      operation: subtract

  pcb:
    main:
      what: outline
      name: base_outline

  layout_tester:
    main:
      what: outline
      name: pcb
    keys:
      what: rectangle
      where:
        - /matrix_.*/
        - /thumbfan_.*/
      size: [kx - 0.01, ky - 0.01]
      corner: px
      bound: false
      operation: subtract

pcbs:
  board:
    outlines:
      edge:
        outline: pcb
        layer: Edge.Cuts
      # circles:
      #   outline: circles_bottom
      #   layer: Eco1.User
    footprints:
      choc:
        where:
          - /matrix_.*/
          - /thumbfan_.*/
        what: custom/choc
        params:
          from: "{{name}}"
          to: GND
          keycaps: true
          hotswap: true
          hotswap_tht: true
          reverse: true
          traces: true
          assume_ground_fill: true
          keycaps_x: capx
          keycaps_y: capy
      mcu:
        what: custom/nice_nano_pretty
        where: mcu
        params:
          minimal_jumpers: true
          P1: matrix_inner_top
          P0: matrix_inner_home
          P2: matrix_inner_bottom
          P3: matrix_ring_top
          P4: matrix_middle_top
          P5: matrix_middle_home
          P6: matrix_middle_bottom
          P7: matrix_index_bottom
          P8: matrix_index_home
          P9: matrix_index_top
          P10: matrix_thumbfan_far
          P16: matrix_thumbfan_home
          P14: matrix_thumbfan_near
          P15: matrix_pinky_bottom
          P18: matrix_pinky_home
          P19: matrix_pinky_top
          P20: matrix_ring_bottom
          P21: matrix_ring_home
      slider_l:
        what: custom/slider
        where: slider
        adjust.rotate: 270
        params:
          side: F
          from: Braw
          left: RAW
      slider_r:
        what: custom/slider
        where: slider
        adjust.rotate: 270
        params:
          side: B
          from: Braw
          right: RAW
          skip_thruholes: true # avoid overlapping thruholes
      jst_bat:
        what: custom/jst_bat
        where: jst_bat
        params:
          reverse: true
          pos: Braw
          neg: GND
      reset:
        what: custom/reset
        where: reset
        adjust.rotate: 270
        params:
          from: GND
          to: RST
      info_l:
        what: custom/text
        where: info
        params:
          text: "rae-dux v1.0\\nby ajrae"
          justify: left
      info_r:
        what: custom/text
        where: info
        params:
          layer: B.SilkS
          text: "rae-dux v1.0\\nby ajrae"
          justify: mirror right

      # traces to make things prettier??
      pinky_top_t:
        what: custom/trace
        adjust:
          ref: matrix_pinky_top
          shift: [ 5 + 1.2 + 3*0.5001, -3.8 - 1]
        params:
          net: matrix_pinky_top
          side: F
          y_end: 1.2 ky
      pinky_home_t:
        what: custom/trace
        adjust:
          ref: matrix_pinky_home
          shift: [ 5 + 1.2 + 2*0.5001, -3.8 - 1]
        params:
          net: matrix_pinky_home
          side: F
          y_end: 0.2 ky
      ring_top_t:
        what: custom/trace
        adjust:
          ref: matrix_ring_top
          shift: [ 5 + 1.2 + 3*0.5001, -3.8 - 1]
        params:
          net: matrix_ring_top
          side: F
          y_end: 2.2 ky
      ring_home_t:
        what: custom/trace
        adjust:
          ref: matrix_ring_home
          shift: [ 5 + 1.2 + 2*0.5001, -3.8 - 1]
        params:
          net: matrix_ring_home
          side: F
          y_end: 1.2 ky
      ring_bottom_t:
        what: custom/trace
        adjust:
          ref: matrix_ring_bottom
          shift: [ 5 + 1.2 + 1*0.5001, -3.8 - 1]
        params:
          net: matrix_ring_bottom
          side: F
          y_end: 0.2 ky
      middle_top_t:
        what: custom/trace
        adjust:
          ref: matrix_middle_top
          shift: [ 5 + 1.2 + 3*0.5001, -3.8 - 1]
        params:
          net: matrix_middle_top
          side: F
          y_end: 2.5 ky
      middle_home_t:
        what: custom/trace
        adjust:
          ref: matrix_middle_home
          shift: [ 5 + 1.2 + 2*0.5001, -3.8 - 1]
        params:
          net: matrix_middle_home
          side: F
          y_end: 1.5 ky
      middle_bottom_t:
        what: custom/trace
        adjust:
          ref: matrix_middle_bottom
          shift: [ 5 + 1.2 + 1*0.5001, -3.8 - 1]
        params:
          net: matrix_middle_bottom
          side: F
          y_end: 0.5 ky
      index_top_t:
        what: custom/trace
        adjust:
          ref: matrix_index_top
          shift: [ 5 + 1.2 + 3*0.5001, -3.8 - 1]
        params:
          net: matrix_index_top
          side: F
          y_end: 2.3 ky
      index_home_t:
        what: custom/trace
        adjust:
          ref: matrix_index_home
          shift: [ 5 + 1.2 + 2*0.5001, -3.8 - 1]
        params:
          net: matrix_index_home
          side: F
          y_end: 1.3 ky
      index_bottom_t:
        what: custom/trace
        adjust:
          ref: matrix_index_bottom
          shift: [ 5 + 1.2 + 1*0.5001, -3.8 - 1]
        params:
          net: matrix_index_bottom
          side: F
          y_end: 0.3 ky
