meta:
  engine: 4.0.4
  name: rae-dux
  version: 0.5
  author: ajrae

presets:
  defaults:
    capx: 17
    capy: 16
    kx: cx
    ky: cy
    px: 2
    py: 2
    one: 1
    pi: 3.141592654
    pinky_splay: 17
    ring_splay: -7
    home_splay: -7
    index_splay: -3
    ts: 0.5001 # trace spacing

  choc_spaced:
    $extends: presets.defaults

  mx_spaced:
    $extends: presets.defaults
    capx: 18
    capy: 18
    kx: 19
    ky: 19

units:
  $extends: presets.mx_spaced

points:
  # Actual key points
  zones.matrix:
    anchor.shift: [150, -180]
    key:
      padding: ky
      trace_target: bottom
      extra_toff: "0"
    rows:
      bottom:
        trace_offset_x: 1 + 1ts
        trace_offset_y: 1 + 1ts
        trace_length: 0ky
        row_idx: (2)
      home:
        trace_offset_x: 1 + 2ts
        trace_offset_y: 1 + 2ts
        trace_length: 1ky
        row_idx: (1)
      top:
        trace_offset_x: 1 + 3ts
        trace_offset_y: 1 + 3ts
        trace_length: 2ky
        row_idx: (0)
    columns:
      pinky.key:
        spread: kx
        splay: pinky_splay
        origin: [0, -ky]
        col_idx: (3)
        trace_target: home
      pinky.rows.bottom:
          trace_offset_x: 1 + 4ts
          trace_offset_y: -(1 + 4ts)
          extra_toff: -0.3ky
      ring.key:
        spread: kx
        stagger: 0.95ky
        splay: ring_splay
        origin: [0, -ky]
        col_idx: (2)
      middle.key:
        spread: kx
        stagger: ky/3
        splay: home_splay
        origin: [0, -ky]
        shift: [0.2, 0]
        bind: 0
        col_idx: (1)
      index.key:
        spread: kx
        stagger: -ky/3
        splay: index_splay
        origin: [0, -ky]
        col_idx: (0)
      inner.key:
        spread: kx
        stagger: -ky/6
        origin: [0, -ky]
        # no col idx
  zones.thumbfan:
    anchor:
      ref: matrix_inner_bottom
      shift: [-0.25 * kx, -1.4 * ky]
    columns:
      near.key:
        spread: kx
        splay: -5
        origin: [-1.5 * kx, -0.5 * ky]
      home.key:
        spread: kx
        splay: -8
        origin: [-0.5 * kx, -0.5 * ky]
      far.key:
        spread: kx
        splay: -20
        origin: [-0.5 * kx, -0.5 * ky]
    rows.thumb:

  # Component points
  zones.mcu:
    anchor:
      ref: matrix_inner_top
      shift: [20, -36/2 + 0.4 ky]
  zones.reset:
    anchor:
      ref: matrix_inner_bottom
      shift: [27.5, -14]
  zones.slider:
    anchor:
      ref: matrix_inner_bottom
      shift: [28, 0]
  zones.jst_bat:
    anchor:
      ref: reset
      shift: [-7.5, -3.25]
  zones.info:
    anchor:
      ref: thumbfan_near_thumb
      shift: [ -1.1 kx, -0.4 ky ]

  # Trace points
  zones.bus_elbow_lower:
    anchor:
      ref: matrix_inner_bottom
      shift: [6, -0.55ky]
  zones.bus_elbow_upper:
    anchor:
      ref: mcu
      shift: [-7ts, -36/2]

  # Outline points
  zones.outline_top_right:
    anchor:
      ref: mcu
      shift: [10, 36/2]
  zones.outline_top_left:
    anchor:
      ref: matrix_ring_top
      shift: [-1.6kx, 0.4ky] # this is arbitrary
  zones.outline_bottom_left:
    anchor:
      ref: matrix_pinky_bottom
      shift: [-0.5kx - 0.2px, -0.5ky - 0.5py]
  zones.outline_thumb_top:
    anchor:
      ref: thumbfan_far_thumb
      shift: [0.5 kx - 0.5px, 0.5 ky + 0.5 py]
  zones.outline_thumb_bottom:
    anchor:
      ref: thumbfan_far_thumb
      shift: [0.5 kx - 0.5px, -0.5 ky - 0.5 py]

outlines:
  raw:
    - what: rectangle
      where:
        - /matrix_.*/
        - /thumbfan_.*/
      size: [kx + px, ky + py]
      corner: px
      bound: true

  thumbfan_glue:
    - what: polygon
      points:
        - ref: matrix_inner_home
        - ref: outline_top_right
          shift: [0.0001, 0] # Needs a little extra offset to the right
        - ref: reset
          shift: [0, -4]
        - ref: outline_thumb_top
        - ref: outline_thumb_bottom
        - ref: matrix_pinky_bottom
          shift: [-0.5kx, -0.5ky]

  circles_top:
    top:
      what: circle
      adjust:
        aggregate:
          method: midpoint
          parts:
            - ref: outline_top_right
            - ref: outline_top_left
            - ref: matrix_middle_top
              shift: [0, 0.5 ky + py]
      radius:
        ref: outline_top_right
    side:
      what: circle
      operation: intersect
      adjust:
        aggregate:
          method: midpoint
          parts:
            - ref: outline_bottom_left
            - ref: outline_top_left
            - ref: matrix_pinky_top
              shift: [-0.5 kx - px, 0.5 ky + py]
      radius:
        ref: outline_bottom_left
    cutoff_controller:
      what: rectangle
      operation: subtract
      adjust:
        ref: outline_top_right
        shift: [80/2, -200/2]
      size: [80, 200]

  circles_bottom:
    bottom:
      what: circle
      adjust:
        aggregate:
          method: midpoint
          parts:
            - ref: outline_bottom_left
            - ref: outline_thumb_bottom
            - ref: thumbfan_near_thumb
              shift: [-0.5 kx - px, -0.5 ky - py]
      radius:
        ref: outline_bottom_left
    cutoff_thumbfan:
      what: rectangle
      operation: subtract
      adjust:
        ref: outline_thumb_bottom
        shift: [30/2, 0]
      size: [30, 60]

  base_outline:
    main:
      what: outline
      name: raw
      fillet: 15
    thumbfan_glue:
      what: outline
      name: thumbfan_glue
      operation: add
    circles_top:
      what: outline
      name: circles_top
      operation: add
      fillet: 15
    circles_bottom:
      what: outline
      name: circles_bottom
      operation: subtract

  pcb:
    main:
      what: outline
      name: base_outline

  layout_tester:
    main:
      what: outline
      name: pcb
    keys:
      what: rectangle
      where:
        - /matrix_.*/
        - /thumbfan_.*/
      size: [kx - 0.01, ky - 0.01]
      corner: px
      bound: false
      operation: subtract

pcbs:
  board:
    outlines:
      edge:
        outline: pcb
        layer: Edge.Cuts
      # circles:
      #   outline: circles_bottom
      #   layer: Eco1.User
    footprints:
      choc:
        where:
          - /matrix_.*/
          - /thumbfan_.*/
        what: custom/choc
        params:
          from: "{{name}}"
          to: GND
          keycaps: true
          hotswap: true
          hotswap_tht: true
          reverse: true
          traces: false
          assume_ground_fill: true
          keycaps_x: capx
          keycaps_y: capy
      mcu:
        what: custom/nice_nano_pretty
        where: mcu
        params:
          minimal_jumpers: true
          traces: false
          P1: matrix_inner_top
          P0: matrix_inner_home
          P2: matrix_inner_bottom
          P3: matrix_ring_top
          P4: matrix_middle_bottom
          P5: matrix_middle_home
          P6: matrix_middle_top
          P7: matrix_index_bottom
          P8: matrix_index_home
          P9: matrix_index_top
          P10: thumbfan_far_thumb
          P16: thumbfan_home_thumb
          P14: thumbfan_near_thumb
          P15: matrix_pinky_bottom
          P18: matrix_pinky_home
          P19: matrix_pinky_top
          P20: matrix_ring_bottom
          P21: matrix_ring_home
      slider_l:
        what: custom/slider
        where: slider
        adjust.rotate: 270
        params:
          side: F
          from: Braw
          left: RAW
      slider_r:
        what: custom/slider
        where: slider
        adjust.rotate: 270
        params:
          side: B
          from: Braw
          right: RAW
          skip_thruholes: true # avoid overlapping thruholes
      jst_bat:
        what: custom/jst_bat
        where: jst_bat
        params:
          reverse: true
          pos: Braw
          neg: GND
      reset:
        what: custom/reset
        where: reset
        adjust.rotate: 270
        params:
          from: GND
          to: RST
      info_l:
        what: custom/text
        where: info
        params:
          text: "rae-dux v1.0\\nby ajrae"
          justify: left
      info_r:
        what: custom/text
        where: info
        params:
          layer: B.SilkS
          text: "rae-dux v1.0\\nby ajrae"
          justify: mirror right

      inter_key_to:
        what: custom/router
        where:
          - /matrix_.*/
        params:
          net: GND
          route: |
            - point: [-8.275, -3.75]
              point_type: relative
              layer: F.Cu
            - point: [0, 0.75ry]
              point_type: offset
            - point: [0.25rx, 0.25ry]
              point_type: offset
            - point: [0, 5.9]
              point_type: relative

      inter_key_from:
        what: custom/router
        where:
          - /matrix_.*/
        params:
          net: "{{name}}"
          route: |
            - point: [3.075, -5.95]
              point_type: relative
              layer: F.Cu
            - point: [0, ry-rx] # gets 45 deg angle in
              point_type: offset
            - point: [5, 3.8]
              point_type: relative
            - point: [-5, 3.8]
              point_type: relative
            - point: [rx, -rx] # gets 45 deg angle out
              point_type: offset
              layer: B.Cu
            - point: [-3.075, -5.95]
              point_type: relative

      matrix_to_bus_traces:
        what: custom/router
        where:
          - /matrix_ring.*/
          - /matrix_middle.*/
          - /matrix_index.*/
          - /matrix_pinky.*/
        adjust:
          shift: [5, -3.8]
        params:
          net: "{{name}}"
          route: |
            - point: [0, 0]
              point_type: relative
              layer: F.Cu
            - point: [{{trace_offset_x}}, {{trace_offset_y}}]
              point_type: offset
            - point:
                ref: {{zone.name}}_{{col.name}}_{{trace_target}}
                shift: [5 + {{trace_offset_x}}, -0.5ky + {{trace_offset_y}} + {{extra_toff}}]
              point_type: anchor
              rotate: -r
            - point: [0.2rx, ry]
              point_type: offset
            - point:
                ref: bus_elbow_lower
                shift: [ts*atan(pi/4)({{col_idx}}*3 + {{row_idx}}), -ts*({{col_idx}}*3 + {{row_idx}})]
              point_type: anchor
            - point: [rx, -rx]
              point_type: offset
            - point:
                ref: bus_elbow_upper
                shift: [ts*({{col_idx}}*3 + {{row_idx}}), 0]
              point_type: anchor
