meta:
  engine: 4.0.4
  name: rae-dux
  version: 0.5
  author: ajrae

presets:
  defaults:
    capx: 17
    capy: 16
    kx: cx
    ky: cy
    px: 2
    py: 2
    pinky_splay: 17
    ring_splay: -7
    home_splay: -7
    index_splay: -3
    top_radius: 123
    side_radius: 75
    side_xoff: 0.01
    side_yoff: 0.52


  choc_spaced:
    $extends: presets.defaults

  mx_spaced:
    $extends: presets.defaults
    capx: 18
    capy: 18
    kx: 19
    ky: 19
    top_radius: 136.5
    side_radius: 89.5
    side_xoff: 0.5
    side_yoff: 0.68

units:
  $extends: presets.mx_spaced

points:
  zones:
    matrix:
      anchor.shift: [150, -180]
      key:
        padding: ky
      columns:
        pinky:
          key:
            spread: kx
            splay: pinky_splay
            origin: [0, -ky]
          rows:
            bottom:
              column_net: P15
            home:
              column_net: P18
            top:
              column_net: P19
        ring:
          key:
            spread: kx
            stagger: ky
            splay: ring_splay
            origin: [0, -ky]
          rows:
            bottom:
              column_net: P20
            home:
              column_net: P21
            top:
              column_net: P3
        home:
          key:
            spread: kx
            stagger: ky/3
            splay: home_splay
            origin: [0, -ky]
            shift: [0.2, 0]
            bind: 0
          rows:
            bottom:
              column_net: P4
            home:
              column_net: P5
            top:
              column_net: P6
        index:
          key:
            spread: kx
            stagger: -ky/3
            splay: index_splay
            origin: [0, -ky]
          rows:
            bottom:
              column_net: P7
            home:
              column_net: P8
            top:
              column_net: P9
        inner:
          key:
            spread: kx
            stagger: -ky/6
            origin: [0, -ky]
          rows:
            bottom:
              column_net: P1
            home:
              column_net: P0
            top:
              column_net: P2
    thumbfan:
      anchor:
        ref: matrix_inner_bottom
        shift: [-0.25 * kx, -1.4 * ky]
      columns:
        near:
          key:
            spread: kx
            splay: -5
            origin: [-1.5 * kx, -0.5 * ky]
            column_net: P14
        home:
          key:
            spread: kx
            splay: -8
            origin: [-0.5 * kx, -0.5 * ky]
            column_net: P16
        far:
          key:
            spread: kx
            splay: -20
            origin: [-0.5 * kx, -0.5 * ky]
            column_net: P10
      rows:
        thumb:
          row_net: P7

outlines:
  raw:
    - what: rectangle
      where: true
      size: [kx + px, ky + py]
      corner: px
      bound: true
  thumbfan_glue:
    - what: polygon
      points:
        - ref: matrix_inner_home
        - ref: thumbfan_far_thumb
          shift: [0.5 kx - 0.5px, 0.5 ky + 0.5 py]
        - ref: thumbfan_far_thumb
          shift: [0.5 kx - 0.5px, -0.5 ky - 0.5 py]
        - ref: thumbfan_near_thumb
          shift: [-0.5 kx - px, -0.5 ky - py]
        - ref: matrix_pinky_bottom
          shift: [0.5 kx - 0.5 py, -0.5 ky - 0.5 py]
        - ref: matrix_pinky_home
        - ref: matrix_inner_bottom
          shift: [0.5 kx + 0.5px, 0.5 ky + 0.5 py]
  controller_area:
    main:
      what: rectangle
      adjust:
        ref:
          - matrix_inner_top
        shift: [30/2, -76.5/2 + 0.4 ky]
      size: [30, 76.5]
      corner: px
  circles:
    top:
      what: circle
      adjust:
        ref:
          - matrix_index_bottom
        shift: [-0.45 kx, -4.25 ky]
      radius: top_radius
    side:
      what: circle
      operation: intersect
      adjust:
        ref:
          - matrix_index_bottom
        shift: [side_xoff * kx, side_yoff ky]
      radius: side_radius
    bottom:
      what: circle
      operation: subtract
      adjust:
        ref:
          - matrix_index_bottom
        shift: [-0.5kx, -8.8ky]
      radius: top_radius
    cutoff:
      what: rectangle
      operation: subtract
      adjust:
        ref:
          - matrix_inner_top
        shift: [80/2 + 29.999, 0]
      size: [80, 200]
  base_outline:
    main:
      what: outline
      name: raw
      fillet: 2
    thumbfan_glue:
      what: outline
      name: thumbfan_glue
      operation: add
    controller_area:
      what: outline
      name: controller_area
      operation: add
    circles:
      what: outline
      name: circles
      operation: add
  pcb:
    main:
      what: outline
      name: base_outline
      fillet: 15
  layout_tester:
    main:
      what: outline
      name: pcb
    keys:
      what: rectangle
      where: true
      size: [kx - 0.01, ky - 0.01]
      corner: px
      bound: false
      operation: subtract

pcbs:
  board:
    outlines:
      edge:
        outline: pcb
        layer: Edge.Cuts
      circles:
        outline: circles
        layer: Eco1.User
    footprints:
      choc:
        where: true
        what: custom/choc
        params:
          from: "{{column_net}}"
          to: GND
          keycaps: true
          hotswap: true
          hotswap_tht: true
          reverse: true
          traces: true
          assume_ground_fill: true
          keycaps_x: capx
          keycaps_y: capy
      mcu:
        what: custom/nice_nano_pretty
        params:
          minimal_jumpers: true
        adjust:
          ref:
            - matrix_inner_top
          shift: [20, -36/2 + 0.4 ky]
          rotate: 0
      slider_l:
        what: custom/slider
        adjust:
          ref:
            - matrix_inner_bottom
          shift: [28, 0]
          rotate: 270
        params:
          side: F
          from: Braw
          left: RAW
      slider_r:
        what: custom/slider
        adjust:
          ref:
            - matrix_inner_bottom
          shift: [28, 0]
          rotate: 270
        params:
          side: B
          from: Braw
          right: RAW
          skip_thruholes: true # avoid overlapping thruholes
      jst_bat:
        what: custom/jst_bat
        adjust:
          ref:
            - matrix_inner_bottom
          shift: [20, -17.5]
        params:
          reverse: true
          pos: Braw
          neg: GND
      reset:
        what: custom/reset
        adjust:
          ref:
            - matrix_inner_bottom
          shift: [27.5, -14]
          rotate: 270
        params:
          from: GND
          to: RST
      info_l:
        what: custom/text
        adjust:
          ref:
            - thumbfan_near_thumb
          shift: [ -1.1 kx, -0.4 ky ]
          rotate: -3.8
        params:
          text: "rae-dux v1.0\\nby ajrae"
          justify: left
      info_r:
        what: custom/text
        adjust:
          ref:
            - thumbfan_near_thumb
          shift: [ -1.1 kx, -0.4 ky]
          rotate: -3.8
        params:
          layer: B.SilkS
          text: "rae-dux v1.0\\nby ajrae"
          justify: mirror right
